employees/urls.py
from django.urls import path
from . import views

app_name = 'employees'

urlpatterns = [
	path('<str:emp_type>/create', views.create_employee, name='employee_create'),
	path('create/<slug:slug>', views.edit_employee, name='employee_edit'),
	path('<slug:slug>/delete', views.EmployeeDeleteView.as_view(), name='employee_delete'),
	path('all', views.EmployeeListView.as_view(), name='employees_list'),
	path('<slug:slug>', views.EmployeeDetailView.as_view(), name='employee_detail'),
]

home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
	path('', views.AuthenticateView.as_view(), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	path('home/', views.dashboard, name='dashboard'),
	path('password/', views.PasswordView.as_view(), name='password_change'),
	# path('password/done', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
	path('edit/', views.edit, name='edit'),
]

models/urls.py
from django.urls import path
from . import views

app_name = 'models'

urlpatterns = [
	path('create', views.CreateModelView.as_view(), name='create_model'),
	path('<slug:slug>/update', views.UpdateModelView.as_view(), name='update_model'),
	path('portfolio/<int:pk>', views.PortfolioDetailView.as_view(), name='portfolio_detail'),
	path('portfolio/<int:pk>/upload', views.PhotoCreateView.as_view(), name='create_photo'),
	path('photo/<uuid:pk>/delete', views.PhotoDeleteView.as_view(), name='photo_delete'),
	path('measures/<int:pk>', views.MeasuresUpdateView.as_view(), name='update_measures'),
	path('all', views.ModelListView.as_view(), name='model_list'),
	path('detail/<slug:slug>', views.ModelDetailView.as_view(), name='model_detail'),
	path('agencies/create', views.CreateAgencyView.as_view(), name='create_agency'),
	path('agencies/all', views.AgencyListView.as_view(), name='agency_list'),
	path('agencies/<slug:slug>', views.AgencyDetailView.as_view(), name='agency_detail'),
	path('agencies/<slug:slug>/update', views.UpdateAgencyView.as_view(), name='agency_update'),
	path('agencies/<slug:slug>/delete', views.AgencyDeleteView.as_view(), name='agency_delete'),
]

star_rover/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # Apps
    path('employees/', include('employees.urls', namespace='employees')),
    path('events/', include('events.urls', namespace='events')),
    path('models/', include('models.urls', namespace='models')),
    path('', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Profile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	birthday = models.DateField(blank=True, null=True)
	photo = models.ImageField(upload_to='home/%Y/%m/%d', blank=True)

	def __str__(self):
		return f'Profile for user {self.user.username}'

	@property
	def get_photo_url(self):
		if self.photo and hasattr(self.photo, 'url'):
			return self.photo.url
		else:
			return 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png'

home/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User

class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)

class UserEditForm(forms.ModelForm):
	first_name = forms.CharField(
		widget=forms.TextInput(
			attrs={
				'class': 'form-control',
				'placeholder': 'Nombres'
			}
		),
		label='Nombres'
	)
	last_name = forms.CharField(
		widget=forms.TextInput(
			attrs={
				'class': 'form-control',
				'placeholder': 'Apellidos'
			}
		),
		label='Apellidos'
	)
	email = forms.EmailField(
		widget=forms.TextInput(
			attrs={
				'class': 'form-control',
				'placeholder': 'Dirección de e-mail'
			}
		),
		label='Dirección de e-mail'
	)
	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'email')

class ProfileEditForm(forms.ModelForm):
	birthday = forms.CharField(
		widget=forms.TextInput(
			attrs={
				'class': 'form-control',
				'data-provide': 'datepicker',
				'data-date-autoclose': 'true',
				'data-date-container': '#birthday',
				'data-date-format': 'yyyy-mm-d'
			}
		),
		label='Fecha de nacimiento'
	)
	photo = forms.ImageField(
		widget=forms.FileInput(
			attrs={
				'class': 'form-control'
			}
		)
	)
	class Meta:
		model = Profile
		fields = ('birthday', 'photo')

home/views.py
from django.shortcuts import render
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.urls import reverse_lazy
from events.models import Event
from .models import Profile
from .forms import UserEditForm, ProfileEditForm


# Create your views here.
class AuthenticateView(LoginView):
	redirect_authenticated_user = True

class PasswordView(SuccessMessageMixin, PasswordChangeView):
	success_message = '¡Tu password ha sido cambiado exitosamente!'
	success_url = reverse_lazy('dashboard')

@login_required
def dashboard(request):
	return render(request, 'home/home.html', {'section': 'dashboard'})

@login_required
def edit(request):
	if request.method == 'POST':
		user_form = UserEditForm(instance=request.user,
			data=request.POST)
		profile_form = ProfileEditForm(instance=request.user.profile,
			data=request.POST, files=request.FILES)
		if user_form.is_valid() and profile_form.is_valid():
			user_form.save()
			profile_form.save()
			messages.add_message(request, messages.SUCCESS, 'Tu perfil ha sido editado exitosamente.')
	else:
		user_form = UserEditForm(instance=request.user)
		profile_form = ProfileEditForm(instance=request.user.profile)
	return render(request, 'home/edit.html', {
		'user_form': user_form,
		'profile_form': profile_form
		})

home/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% block css %}
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-hot-purple">
        <div class="container-fluid">
            <a class="navbar-brand style-script ms-4" href="{% if request.user.is_authenticated %}{% url 'dashboard' %}{% else %}{% url 'login' %}{% endif %}">The Star Rover</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            {% if not request.user.is_authenticated %}
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                </ul>
                <button class="btn btn-outline-fuchsia me-4" data-bs-toggle="modal" data-bs-target="#loginModal">Iniciar sesión</button>
            </div>
            {% else %}
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown">
                            Empleados
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'employees:employee_create' 'regular' %}" class="dropdown-item">Registrar empleado raso</a>
                            </li>
                            <li>
                                <a href="{% url 'employees:employee_create' 'directive' %}" class="dropdown-item">Registrar empleado directivo</a>
                            </li>
                            <li>
                                <a href="{% url 'employees:employees_list' %}" class="dropdown-item">Ver todos los empleados</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" href="#">Eventos</a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#" class="dropdown-item">Registrar evento</a>
                            </li>
                            <li>
                                <a href="#" class="dropdown-item">Ver todos los eventos</a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a href="#" class="dropdown-item">Registrar desfile</a>
                            </li>
                            <li>
                                <a href="#" class="dropdown-item">Ver todos los desfiles</a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a href="#" class="dropdown-item">Registrar diseñador</a>
                            </li>
                            <li>
                                <a href="#" class="dropdown-item">Ver todos los diseñadores</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" href="#">Artistas</a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="#" class="dropdown-item">Registrar artista</a>
                            </li>
                            <li>
                                <a href="#" class="dropdown-item">Ver todos los artistas</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" href="#">Nuestras Modelos</a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'models:create_model' %}" class="dropdown-item">Registrar modelo</a>
                            </li>
                            <li>
                                <a href="{% url 'models:model_list' %}" class="dropdown-item">Ver todas las modelos</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown">Agencias de modelaje</a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'models:create_agency' %}" class="dropdown-item">Registrar agencia</a>
                            </li>
                            <li>
                                <a href="{% url 'models:agency_list' %}" class="dropdown-item">Ver todas las agencias</a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown ms-auto me-lg-4">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <img src="{{ request.user.profile.get_photo_url }}" alt="" class="img-fluid avatar-xs me-1" style="object-fit: cover;">
                            {{ request.user.first_name }} {{ request.user.last_name }}
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'edit' %}" class="dropdown-item">Editar mi perfil</a>
                            </li>
                            <li>
                                <a href="{% url 'password_change' %}" class="dropdown-item">Cambiar mi password</a>
                            </li>
                        </ul>
                    </li>
                </ul>
                <a class="btn btn-outline-fuchsia me-4" href="{% url 'logout' %}">Cerrar sesión</a>
            </div>
            {% endif %}
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    {% block modal %}
    {% endblock %}
    {% if messages %}
    <div class="modal fade" id="messageModal" role="dialog">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body text-center align-items-center">
                    <div class="logout-icon m-auto">
                        <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                        viewBox="0 0 161.2 161.2" enable-background="new 0 0 161.2 161.2" xml:space="preserve">
                            <path class="path" fill="none" stroke="#9e74e6" stroke-miterlimit="10" d="M425.9,52.1L425.9,52.1c-2.2-2.6-6-2.6-8.3-0.1l-42.7,46.2l-14.3-16.4
                                c-2.3-2.7-6.2-2.7-8.6-0.1c-1.9,2.1-2,5.6-0.1,7.7l17.6,20.3c0.2,0.3,0.4,0.6,0.6,0.9c1.8,2,4.4,2.5,6.6,1.4c0.7-0.3,1.4-0.8,2-1.5
                                c0.3-0.3,0.5-0.6,0.7-0.9l46.3-50.1C427.7,57.5,427.7,54.2,425.9,52.1z"/>
                            <circle class="path" fill="none" stroke="#dd80e6" stroke-width="4" stroke-miterlimit="10" cx="80.6" cy="80.6" r="62.1"/>
                            <polyline class="path" fill="none" stroke="#f075ba" stroke-width="6" stroke-linecap="round" stroke-miterlimit="10" points="113,52.8
                                74.1,108.4 48.2,86.4 "/>
                    
                            <circle class="spin" fill="none" stroke="#e67078" stroke-width="4" stroke-miterlimit="10" stroke-dasharray="12.2175,12.2175" cx="80.6" cy="80.6" r="73.9"/>
                        </svg>
                    </div> 
                    <h3>¡Genial!</h3>
                    {% for message in messages %}
                    <p class="text-{{ message.tags }}">{{ message }}</p>
                    {% endfor %}
                    <hr>
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    <script src="{% static 'js/vendor.js'%}" type="text/javascript"></script>
    <script src="{% static 'js/app.js'%}" type="text/javascript"></script>
    <script src="{% static 'js/ui/component.todo.js'%}" type="text/javascript"></script>
    <script src="{% static 'js/messages.js'%}" type="text/javascript"></script>
    {% block js %}
    {% endblock %}
</body>
</html>