home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
	path('', views.AuthenticateView.as_view(), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	path('home/', views.dashboard, name='dashboard'),
	path('password/', views.PasswordView.as_view(), name='password_change'),
	# path('password/done', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
	path('edit/', views.edit, name='edit'),
]

models/urls.py
from django.urls import path
from . import views

app_name = 'models'

urlpatterns = [
	path('create', views.CreateModelView.as_view(), name='create_model'),
	path('<slug:slug>/update', views.UpdateModelView.as_view(), name='update_model'),
	path('portfolio/<int:pk>', views.PortfolioDetailView.as_view(), name='portfolio_detail'),
	path('portfolio/<int:pk>/upload', views.PhotoCreateView.as_view(), name='create_photo'),
	path('photo/<uuid:pk>/delete', views.PhotoDeleteView.as_view(), name='photo_delete'),
	path('measures/<int:pk>', views.MeasuresUpdateView.as_view(), name='update_measures'),
	path('all', views.ModelListView.as_view(), name='model_list'),
	path('detail/<slug:slug>', views.ModelDetailView.as_view(), name='model_detail'),
	path('agencies/create', views.CreateAgencyView.as_view(), name='create_agency'),
	path('agencies/all', views.AgencyListView.as_view(), name='agency_list'),
	path('agencies/<slug:slug>', views.AgencyDetailView.as_view(), name='agency_detail'),
	path('agencies/<slug:slug>/update', views.UpdateAgencyView.as_view(), name='agency_update'),
	path('agencies/<slug:slug>/delete', views.AgencyDeleteView.as_view(), name='agency_delete'),
]

star_rover/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # Apps
    path('employees/', include('employees.urls', namespace='employees')),
    path('events/', include('events.urls', namespace='events')),
    path('models/', include('models.urls', namespace='models')),
    path('', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employees/models.py
import uuid

from django.db import models
from django.core.exceptions import ObjectDoesNotExist
from django.utils.text import slugify

# Create your models here.
class Employee(models.Model):
	"""
	Base class for all employees in the application.
	This class should never be created standalone, but
	only when creating a RegularEmployee or DirectiveEmployee
	instance as well.
	"""
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)
	slug = models.SlugField(unique=True, blank=True, null=True)
	phone_number = models.CharField(max_length=10)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ['created']

	def get_type(self):
		try:
			obj = RegularEmployee.objects.get(employee=self)
			if obj:
				return 'Raso'
		except ObjectDoesNotExist as e:
			try:
				obj = DirectiveEmployee.objects.get(employee=self)
				if obj:
					return 'Directivo'
			except ObjectDoesNotExist as e:
				return 'N/A'

	def save(self, *args, **kwargs):
		name = self.first_name + ' ' + self.last_name
		self.slug = slugify(name)
		super().save(*args, **kwargs)

	def __str__(self):
		return f'{self.first_name} {self.last_name}'

class RegularEmployee(models.Model):
	"""
	Regular Employee model. This kind of employee will be
	tasked with loading Events into the application.
	"""
	employee = models.OneToOneField(Employee, on_delete=models.CASCADE)
	salary = models.PositiveBigIntegerField()

class DirectiveEmployee(models.Model):
	"""
	Directive Employee model. This kind of employee will be
	assigned to each event and gets paid for directing said
	event.
	"""
	employee = models.OneToOneField(Employee, on_delete=models.CASCADE, null=True, blank=True)
	graduated_from = models.CharField(max_length=256)

events/models.py
import uuid
from datetime import date

from django.db import models
from django_countries.fields import CountryField

from employees.models import DirectiveEmployee, RegularEmployee
# Dependency Injection
SOLO_GROUP = (
    ('soloist', 'Soloist'),
    ('group', 'Group'),
)
# Create your models here.
class Event(models.Model):
    """
    Event model. Each event will feature multiple parades.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=256)
    slug = models.SlugField(db_index=True)
    start_date = models.DateField(default=date.today)
    end_date = models.DateField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    directive = models.ForeignKey(
        DirectiveEmployee,
        on_delete=models.CASCADE,
        related_name='event_directive'
    )
    employees = models.ManyToManyField(RegularEmployee, related_name='event_employees')

    class Meta:
        ordering = ['-created']

class Designer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    passport = models.CharField(max_length=20)
    country = CountryField()

    class Meta:
        ordering = ['last_name']

class Parade(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='parade_event')
    designer = models.ForeignKey(Designer, on_delete=models.CASCADE, related_name='parade_designer')
    date = models.DateField()
    time = models.TimeField()
    collection = models.CharField(max_length=256)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    ended = models.BooleanField(default=False)

    class Meta:
        ordering = ['date']

class Genre(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        ordering = ['name']

class Artist(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    artist_name = models.CharField(max_length=256)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE, related_name='artist_genre')
    contract = models.BooleanField(default=False)
    salary = models.PositiveIntegerField()

    class Meta:
        ordering = ['artist_name']

class Group(models.Model):
    artist = models.OneToOneField(Artist, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

class Soloist(models.Model):
    artist = models.OneToOneField(Artist, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, models.DO_NOTHING, blank=True, null=True)

home/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Profile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	birthday = models.DateField(blank=True, null=True)
	photo = models.ImageField(upload_to='home/%Y/%m/%d', blank=True)

	def __str__(self):
		return f'Profile for user {self.user.username}'

	@property
	def get_photo_url(self):
		if self.photo and hasattr(self.photo, 'url'):
			return self.photo.url
		else:
			return 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png'

models/admin.py
from django.contrib import admin
from .models import ModelAgency, Models, Measurements, Portfolio, Photo

# Register your models here.
@admin.register(Models)
class ModelsAdmin(admin.ModelAdmin):
	list_display = ['id', 'last_name', 'first_name',
		'country', 'active', 'salary']
	list_display_links = ['id']
	list_filter = ['last_name', 'salary']
	list_editable = ['active', 'salary']

@admin.register(ModelAgency)
class AgencyAdmin(admin.ModelAdmin):
	list_display = ['id', 'name', 'country']
	list_display_links = ['id']
	list_filter = ['name', 'country']

@admin.register(Measurements)
class MeasuresAdmin(admin.ModelAdmin):
	list_display = ['measured_model', 'chest', 'waist', 'hips']
	list_display_links = ['measured_model']
	list_filter = ['measured_model', 'chest', 'waist', 'hips']

@admin.register(Portfolio)
class PortfolioAdmin(admin.ModelAdmin):
	list_display = ['model']

@admin.register(Photo)
class PhotoAdmin(admin.ModelAdmin):
	list_display = ['id', 'model_name', 'image']
	list_display_links = ['id']

	@admin.display
	def model_name(self, obj):
		return f'{obj.portfolio.model.first_name} {obj.portfolio.model.last_name}'

models/apps.py
from django.apps import AppConfig


class ModelsConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'models'

models/models.py
import uuid
from django_countries.fields import CountryField
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.
class ModelAgency(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=256)
    slug = models.SlugField(max_length=200, unique=True)
    country = CountryField()
    creation_year = models.DateField()
    email = models.EmailField()
    owner_name = models.CharField(max_length=512)
    parent_agency = models.ForeignKey('self', models.CASCADE, null=True, blank=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'model agencies'

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('models:agency_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(ModelAgency, self).save(*args, **kwargs)

class Models(models.Model):
    # Dependency injection
    EYE_COLORS = (
        (None, 'Selecciona un color...'),
        ('green', 'Verdes'),
        ('blue', 'Azules'),
        ('brown', 'Cafés'),
        ('hazel', 'Miel'),
        ('gray', 'Grises'),
        ('dark', 'Negros'),
        ('other', 'Otro'),
    )
    SKIN_COLORS = (
        (None, 'Selecciona un color...'),
        ('black', 'Negra'),
        ('brown', 'Morena'),
        ('olive', 'Trigueña'),
        ('fair', 'Clara'),
        ('pale', 'Blanca'),
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    country = CountryField()
    birthday = models.DateField()
    eye_color = models.CharField(choices=EYE_COLORS, max_length=10)
    skin_color = models.CharField(choices=SKIN_COLORS, max_length=20)
    height = models.SmallIntegerField()
    shoe_size = models.SmallIntegerField()
    weight = models.SmallIntegerField()
    particularities = models.TextField(null=True, blank=True)
    active = models.BooleanField(default=True)
    salary = models.PositiveIntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    agency = models.ForeignKey(ModelAgency, related_name='model_modelagency', on_delete=models.CASCADE)

    class Meta:
        ordering = ['last_name']

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_absolute_url(self):
        return reverse('models:model_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        name = self.first_name + ' ' + self.last_name
        self.slug = slugify(name)
        super(Models, self).save(*args, **kwargs)
        measures = Measurements.objects.filter(
            measured_model=self
        ).first()
        portfolio = Portfolio.objects.filter(
            model=self
        ).first()
        if not measures:
            Measurements.objects.create(
                measured_model=self
            )
        if not portfolio:
            Portfolio.objects.create(
                model=self
            )


class Measurements(models.Model):
    chest = models.SmallIntegerField(null=True)
    waist = models.SmallIntegerField(null=True)
    hips = models.SmallIntegerField(null=True)
    measured_model = models.ForeignKey(Models, on_delete=models.CASCADE, related_name='model_measures')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']
        verbose_name_plural = 'model measurements'

class Portfolio(models.Model):
    model = models.ForeignKey(Models, on_delete=models.CASCADE, related_name='model_portfolio')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Portfolio for model {self.model}'

class Photo(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE, related_name='photo_portfolio')
    image = models.ImageField(upload_to='products/%Y/%m/%d')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

models/serializers.py
from rest_framework import serializers
from django_countries.serializers import CountryFieldMixin
from .models import ModelAgency

class ModelAgencySerializer(CountryFieldMixin, serializers.ModelSerializer):
	class Meta:
		model = ModelAgency
		fields = ('id', 'name', 'country', 'creation_year', 
			'email', 'owner_name', 'parent_agency')

models/templates/models/modelagency_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/vendor/dataTables.bootstrap4.css' %}">
<link rel="stylesheet" href="{% static 'css/vendor/responsive.bootstrap4.css' %}">
{% endblock %}
{% block title %}The Star Rover - {{ object.name }}{% endblock %}
{% block content %}
<div class="container-fluid">
	<div class="row mx-3 my-3">
		<div class="col-lg-12 col-xl-10 offset-xl-1">
			<h1 class="style-script display-4 text-red">Detalles de la agencia {{ object.name }}</h1>
			<p class="lead">Aquí podrás ver toda la información detallada de la agencia {{ object.name }}.</p>
			<hr>
			<div class="accordion" id="agenciaAccordion">
				<div class="card mb-0">
					<div class="card-header" id="headingOne">
						<h5 class="m-0">
							<a href="#collapseOne" class="custom-accordion-title d-block py-2"
								data-bs-toggle="collapse" aria-expanded="true" aria-controls="collapseOne">
								Información de la agencia	
							</a>
						</h5>
					</div>
					<div class="collapse show" id="collapseOne" data-bs-parent="#agenciaAccordion">
						<div class="card-body">
							<table class="table table-borderless table-hover table-light">
								<tbody>
									<tr>
										<td>
											<strong>Nombre de la agencia</strong>
										</td>
										<td>
											{{ object.name }}
										</td>
									</tr>
									<tr>
										<td>
											<strong>País de origen</strong>
										</td>
										<td>
											{{ object.country.name }}
										</td>
									</tr>
									<tr>
										<td>
											<strong>Fecha de creación</strong>
										</td>
										<td>{{ object.creation_year|date:"d-m-Y" }}</td>
									</tr>
									<tr>
										<td>
											<strong>Correo electrónico</strong>
										</td>
										<td>{{ object.email }}</td>
									</tr>
									<tr>
										<td>
											<strong>Nombre del dueño</strong>
										</td>
										<td>{{ object.owner_name }}</td>
									</tr>
									<tr>
										<td><strong>Agencia padre</strong></td>
										<td>
											{% if object.parent_agency %}
											{{ object.parent_agency }}
											{% else %}
											<span class="text-warning">No tiene</span>
											{% endif %}
										</td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</div>
				<div class="card mb-0">
					<div class="card-header" id="headingTwo">
						<h5 class="m-0">
							<a href="#collapseTwo" class="custom-accordion-title d-block py-2"
								data-bs-toggle="collapse" aria-expanded="true" aria-controls="collapseTwo">
								Modelos de la agencia	
							</a>
						</h5>
					</div>
					<div class="collapse" id="collapseTwo" data-bs-parent="#agenciaAccordion">
						<div class="card-body">
							<table class="table table-borderless table-hover table-light" id="basic-datatable">
								<thead>
									<tr>
										<th>Nombre</th>
										<th>País de origen</th>
										<th>Fecha de nacimiento</th>
										<th>Salario</th>
										<th></th>
									</tr>
								</thead>
								<tbody>
									{% for model in models %}
									<tr>
										<td>{{ model.first_name }} {{ model.last_name }}</td>
										<td>{{ model.country.name }}</td>
										<td>{{ model.birthday|date:"d-m-Y" }}</td>
										<td>${{ model.salary|intcomma }}</td>
										<td><a href="{% url 'models:model_detail' model.slug %}" class="btn btn-outline-primary btn-sm">Detalle</a></td>
									</tr>
									{% empty %}
									<tr>
										<td colspan="4">
											<strong class="text-red text-center align-items-center">No hay modelos pertenecientes a esta agencia.</strong>
										</td>
									</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
			<div class="row mt-3">
				<div class="col">
					<a href="{% url 'models:agency_update' object.slug %}" class="btn btn-warning me-1">Editar datos de agencia</a>
					<a href="{% url 'models:agency_delete' object.slug %}" class="btn btn-danger">Eliminar agencia</a>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block js %}
<!-- Datatables js -->
<script src="{% static 'js/vendor/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/vendor/dataTables.bootstrap4.js' %}"></script>
<script src="{% static 'js/vendor/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'js/vendor/responsive.bootstrap4.min.js' %}"></script>

<!-- Datatable Init js -->
<script src="{% static 'js/pages/demo.datatable-init.js' %}"></script>

{% endblock %}

models/templates/models/models_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %}The Star Rover - {{ object.first_name }} {{ object.last_name}}{% endblock %}
{% block content %}
<div class="container-fluid">
	<div class="row mx-3 my-3">
		<div class="col-lg-12 col-xl-10 offset-xl-1">
			<h1 class="style-script display-4 text-red">Detalles de {{ object.first_name }} {{ object.last_name }}</h1>
			<p class="lead">Aquí podrás ver toda la información detallada de {{ object.first_name }}.</p>
			<hr>
		</div>
	</div>
	<div class="row mt-3">
		<div class="col-12 col-lg-7 col-xl-8">
			<table class="table table-hover table-borderless">
				<tr>
					<th>Nombre completo</th>
					<td>{{ object.first_name }} {{ object.last_name }}</td>
				</tr>
				<tr>
					<th>País de origen</th>
					<td>{{ object.country.name }}</td>
				</tr>
				<tr>
					<th>Fecha de nacimiento</th>
					<td>{{ object.birthday|date:"d-m-Y" }}</td>
				</tr>
				<tr>
					<th>Color de ojos</th>
					<td>{{ object.get_eye_color_display }}</td>
				</tr>
				<tr>
					<th>Color de piel</th>
					<td>{{ object.get_skin_color_display }}</td>
				</tr>
				<tr>
					<th>Estatura</th>
					<td>{{ object.height }} cm</td>
				</tr>
				<tr>
					<th>Talla de zapatos</th>
					<td>{{ object.shoe_size }}</td>
				</tr>
				<tr>
					<th>Peso</th>
					<td>{{ object.weight }} kg</td>
				</tr>
				{% if object.particularities %}
				<tr>
					<th>Particularidades</th>
					<td>{{ object.particularities }}</td>
				</tr>
				{% endif %}
				<tr>
					<th>Salario</th>
					<td>${{ object.salary|intcomma }}</td>
				</tr>
				<tr>
					<th>Agencia a la que pertenece</th>
					<td>
						<a href="{% url 'models:agency_detail' object.agency.slug %}">{{ object.agency.name }}</a>
					</td>
				</tr>
			</table>
		</div>
		<div class="col-12 col-lg-5 col-xl-4">
			<table class="table table-hover table-borderless">
				<thead>
					<tr>
						<th colspan="2">Medidas</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<th>Busto</th>
						<td>{{ measures.chest }}</td>
					</tr>
					<tr>
						<th>Cintura</th>
						<td>{{ measures.waist }}</td>
					</tr>
					<tr>
						<th>Caderas</th>
						<td>{{ measures.hips }}</td>
					</tr>
					<tr>
						<td colspan="2">
							<a href="{% url 'models:update_measures' measures.pk %}">Editar medidas de {{ object.first_name }}</a>
						</td>
					</tr>
				</tbody>
			</table>
			<hr>
			<table class="table table-hover table-borderless">
				<thead>
					<tr>
						<th>Portafolio</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>{{ photos.count }} fotos en el portafolio.</td>
					</tr>
					<tr>
						<td>Última foto agregada el {{ photos.first.created|date:"d-m-Y" }}</td>
					</tr>
					<tr>
						<td>
							<a href="{% url 'models:portfolio_detail' portfolio.pk %}">Ver detalle del portafolio</a>
						</td>
					</tr>
				</tbody>
			</table>
			<div class="d-grid gap-2">
				<a class="btn btn-warning" href="{% url 'models:update_model' object.slug %}">Editar detalles de {{ object.first_name }}</a>
			</div>
		</div>
	</div>
</div>
{% endblock %}

models/templates/models/photo_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}The Star Rover - Eliminar Agencia{% endblock %}
{% block content %}
<div class="container-fluid">
	<div class="row mx-3 my-3">
		<div class="col-lg-12 col-xl-10 offset-xl-1 text-center">
			<h1 class="style-script display-4 text-red">Eliminar foto</h1>
			<p class="lead">Haz clic en el botón de abajo para eliminar la foto.</p>
			<hr>
			<img src="{{ object.image.url }}" alt="" class="img-thumbnail">
			<button class="btn btn-lg btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">Eliminar foto</button>
		</div>
	</div>
</div>
{% endblock %}
{% block modal %}
<div class="modal fade" id="deleteModal" role="dialog">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body text-center align-items-center">
                <h3>¡Cuidado!</h3>
                <p>
                	¿Realmente deseas eliminar la foto? Recuerda que <span class="text-danger">esta acción no puede dehacerse.</span>
                </p>
                <hr>
                <form method="post">
                	{% csrf_token %}
	                <button type="submit" class="btn btn-primary">Sí, deseo eliminarla.</button>
	                <a class="btn btn-secondary" href="{% url 'models:portfolio_detail' object.portfolio.pk %}">No. Quiero regresar.</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

models/templates/models/portfolio_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/vendor/dataTables.bootstrap4.css' %}">
<link rel="stylesheet" href="{% static 'css/vendor/responsive.bootstrap4.css' %}">
{% endblock %}
{% block title %}The Star Rover - Portafolio{% endblock %}
{% block content %}
<div class="container-fluid">
	<div class="row mx-3 my-3">
		<div class="col-lg-12 col-xl-10 offset-xl-1">
			<h1 class="style-script display-4 text-red">Portafolio de  {{ object.model.first_name }} {{ object.model.last_name }}</h1>
			<p class="lead">Aquí podrás ver toda la información del portafolio de {{ object.model.first_name }}.</p>
			<hr>
			<div class="accordion" id="agenciaAccordion">
				<div class="card mb-0">
					<div class="card-header" id="headingOne">
						<h5 class="m-0">
							<a href="#collapseOne" class="custom-accordion-title d-block py-2"
								data-bs-toggle="collapse" aria-expanded="true" aria-controls="collapseOne">
								Información del portafolio	
							</a>
						</h5>
					</div>
					<div class="collapse show" id="collapseOne" data-bs-parent="#agenciaAccordion">
						<div class="card-body">
							<table class="table table-borderless table-hover table-light">
								<tbody>
									<tr>
										<td>
											<strong>Nombre de la modelo</strong>
										</td>
										<td>
											{{ object.model.first_name }} {{ object.model.last_name }}
										</td>
									</tr>
									<tr>
										<td>
											<strong>País de origen</strong>
										</td>
										<td>
											{{ object.model.country.name }}
										</td>
									</tr>
									<tr>
										<td><strong>Agencia</strong></td>
										<td>
											{{ object.model.agency.name }}
										</td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</div>
				<div class="card mb-0">
					<div class="card-header" id="headingTwo">
						<h5 class="m-0">
							<a href="#collapseTwo" class="custom-accordion-title d-block py-2"
								data-bs-toggle="collapse" aria-expanded="true" aria-controls="collapseTwo">
								Fotos del portafolio	
							</a>
						</h5>
					</div>
					<div class="collapse" id="collapseTwo" data-bs-parent="#agenciaAccordion">
						<div class="card-body">
							<table class="table table-borderless table-hover table-light" id="basic-datatable">
								<tbody>
									{% for photo in photos %}
									<tr>
										<td>
											<img src="{{ photo.image.url }}" alt="" class="img-thumbnail avatar-sm">
										</td>
										<td>
											Subida el {{ photo.created|date:"d-m-Y" }}
										</td>
										<td>
											<a href="{{ photo.image.url }}" target="_blank">Link de la imagen</a>
										</td>
										<td>
											<a href="{% url 'models:photo_delete' photo.id %}" class="btn btn-outline-danger">Eliminar</a>
										</td>
									</tr>
									{% empty %}
									<tr>
										<td colspan="2">
											<strong class="text-red text-center align-items-center">No hay fotos en este portafolio aún.</strong>
										</td>
									</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
			<div class="row mt-3">
				<div class="col">
					<a href="{% url 'models:create_photo' object.pk %}" class="btn btn-primary me">Agregar fotos al portafolio</a>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block js %}
<!-- Datatables js -->
<script src="{% static 'js/vendor/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/vendor/dataTables.bootstrap4.js' %}"></script>
<script src="{% static 'js/vendor/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'js/vendor/responsive.bootstrap4.min.js' %}"></script>

<!-- Datatable Init js -->
<script src="{% static 'js/pages/demo.datatable-init.js' %}"></script>

{% endblock %}