employees/urls.py
from django.urls import path
from . import views

app_name = 'employees'

urlpatterns = [
	path('<str:emp_type>/create', views.create_employee, name='employee_create'),
	path('create/<slug:slug>', views.edit_employee, name='employee_edit'),
	path('<slug:slug>/delete', views.EmployeeDeleteView.as_view(), name='employee_delete'),
	path('all', views.EmployeeListView.as_view(), name='employees_list'),
	path('<slug:slug>', views.EmployeeDetailView.as_view(), name='employee_detail'),
]

home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
	path('', views.AuthenticateView.as_view(), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	path('home/', views.dashboard, name='dashboard'),
	path('password/', views.PasswordView.as_view(), name='password_change'),
	# path('password/done', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
	path('edit/', views.edit, name='edit'),
]

models/urls.py
from django.urls import path
from . import views

app_name = 'models'

urlpatterns = [
	path('create', views.CreateModelView.as_view(), name='create_model'),
	path('<slug:slug>/update', views.UpdateModelView.as_view(), name='update_model'),
	path('portfolio/<int:pk>', views.PortfolioDetailView.as_view(), name='portfolio_detail'),
	path('portfolio/<int:pk>/upload', views.PhotoCreateView.as_view(), name='create_photo'),
	path('photo/<uuid:pk>/delete', views.PhotoDeleteView.as_view(), name='photo_delete'),
	path('measures/<int:pk>', views.MeasuresUpdateView.as_view(), name='update_measures'),
	path('all', views.ModelListView.as_view(), name='model_list'),
	path('detail/<slug:slug>', views.ModelDetailView.as_view(), name='model_detail'),
	path('agencies/create', views.CreateAgencyView.as_view(), name='create_agency'),
	path('agencies/all', views.AgencyListView.as_view(), name='agency_list'),
	path('agencies/<slug:slug>', views.AgencyDetailView.as_view(), name='agency_detail'),
	path('agencies/<slug:slug>/update', views.UpdateAgencyView.as_view(), name='agency_update'),
	path('agencies/<slug:slug>/delete', views.AgencyDeleteView.as_view(), name='agency_delete'),
]

star_rover/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # Apps
    path('employees/', include('employees.urls', namespace='employees')),
    path('events/', include('events.urls', namespace='events')),
    path('models/', include('models.urls', namespace='models')),
    path('', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employees/models.py
import uuid

from django.db import models
from django.core.exceptions import ObjectDoesNotExist
from django.utils.text import slugify

# Create your models here.
class Employee(models.Model):
	"""
	Base class for all employees in the application.
	This class should never be created standalone, but
	only when creating a RegularEmployee or DirectiveEmployee
	instance as well.
	"""
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)
	slug = models.SlugField(unique=True, blank=True, null=True)
	phone_number = models.CharField(max_length=10)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	class Meta:
		ordering = ['created']

	def get_type(self):
		try:
			obj = RegularEmployee.objects.get(employee=self)
			if obj:
				return 'Raso'
		except ObjectDoesNotExist as e:
			try:
				obj = DirectiveEmployee.objects.get(employee=self)
				if obj:
					return 'Directivo'
			except ObjectDoesNotExist as e:
				return 'N/A'

	def save(self, *args, **kwargs):
		name = self.first_name + ' ' + self.last_name
		self.slug = slugify(name)
		super().save(*args, **kwargs)

	def __str__(self):
		return f'{self.first_name} {self.last_name}'

class RegularEmployee(models.Model):
	"""
	Regular Employee model. This kind of employee will be
	tasked with loading Events into the application.
	"""
	employee = models.OneToOneField(Employee, on_delete=models.CASCADE)
	salary = models.PositiveBigIntegerField()

class DirectiveEmployee(models.Model):
	"""
	Directive Employee model. This kind of employee will be
	assigned to each event and gets paid for directing said
	event.
	"""
	employee = models.OneToOneField(Employee, on_delete=models.CASCADE, null=True, blank=True)
	graduated_from = models.CharField(max_length=256)

employees/forms.py
from django import forms
from .models import RegularEmployee, DirectiveEmployee
class RegularEmployeeForm(forms.ModelForm):
	use_required_attribute = False
	first_name = forms.CharField(
		widget=forms.TextInput(
			attrs={
				'class': 'form-control',
				'placeholder': 'Nombres'
			}
		),
		label='Nombres'
	)
	last_name = forms.CharField(
		widget=forms.TextInput(
			attrs={
				'class': 'form-control',
				'placeholder': 'Apellidos'
			}
		),
		label='Apellidos'
	)
	phone_number = forms.CharField(
		widget=forms.TextInput(
			attrs={
				'class': 'form-control',
				'placeholder': 'Número de telofono'
			}
		),
		label='Número de teléfono'
	)
	salary = forms.IntegerField(
		widget=forms.TextInput(
			attrs={
				'class': 'form-control',
				'placeholder': 'Salario en pesos (COP)'
			}
		),
		label='Salario en pesos (COP)'
	)

	class Meta:
		model = RegularEmployee
		fields = ['first_name', 'last_name', 'phone_number', 'salary']

class DirectiveEmployeeForm(forms.ModelForm):
	use_required_attribute = False
	first_name = forms.CharField(
		widget=forms.TextInput(
			attrs={
				'class': 'form-control',
				'placeholder': 'Nombres'
			}
		),
		label='Nombres'
	)
	last_name = forms.CharField(
		widget=forms.TextInput(
			attrs={
				'class': 'form-control',
				'placeholder': 'Apellidos'
			}
		),
		label='Apellidos'
	)
	phone_number = forms.CharField(
	widget=forms.TextInput(
			attrs={
				'class': 'form-control',
				'placeholder': 'Número de telofono'
			}
		),
		label='Número de telofono'
	)
	graduated_from = forms.CharField(
	widget=forms.TextInput(
			attrs={
				'class': 'form-control',
				'placeholder': 'Graduado de'
			}
		),
		label='Graduado de'
	)

	class Meta:
		model = DirectiveEmployee
		fields = ['first_name', 'last_name', 'phone_number', 'graduated_from']

employees/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse_lazy, reverse
from django.core.exceptions import ObjectDoesNotExist

from .models import  Employee, RegularEmployee, DirectiveEmployee
from .forms import RegularEmployeeForm, DirectiveEmployeeForm
# Create your views here.

class EmployeeListView(LoginRequiredMixin, ListView):
	model = Employee

	def get_queryset(self, **kwargs):
		return Employee.objects.all()

class EmployeeDetailView(LoginRequiredMixin, DetailView):
	model = Employee

	def get_context_data(self, **kwargs):
		context = super().get_context_data()
		try:
			obj = RegularEmployee.objects.get(employee=self.object)
		except ObjectDoesNotExist as e:
			try:
				obj = DirectiveEmployee.objects.get(employee=self.object)
			except ObjectDoesNotExist as e:
				return None
		context['detail'] = obj
		return context

def create_employee(request, emp_type):
	if request.method == 'POST':
		data = request.POST
		employee = Employee(
			first_name=data['first_name'],
			last_name=data['last_name'],
			phone_number=data['phone_number']
		)
		employee.save()
		if data.get('salary'):
			RegularEmployee.objects.create(employee=employee, salary=data['salary'])
		elif data.get('graduated_from'):
			DirectiveEmployee.objects.create(employee=employee, graduated_from=data['graduated_from'])
		messages.success(request, '¡El empleado ha sido registrado!')
		return HttpResponseRedirect(reverse('employees:employee_detail', kwargs={'slug': employee.slug}))
	else:
		if emp_type == 'regular':
			form = RegularEmployeeForm()
			return render(request, 'employees/employee_form.html', {'form': form, 'type': 'regular'})
		elif emp_type == 'directive':
			form = DirectiveEmployeeForm()
			return render(request, 'employees/employee_form.html', {'form': form, 'type': 'directive'})

def edit_employee(request, slug):
	employee = Employee.objects.get(slug=slug)
	emp_type = ''
	if request.method == 'POST':
		data = request.POST
		salary = data.get('salary')
		graduated_from = data.get('graduated_from')
		if salary:
			emp_form = RegularEmployeeForm(instance=employee, data=request.POST)
		elif graduated_from:
			emp_form = DirectiveEmployeeForm(instance=employee, data=request.POST)
		if emp_form.is_valid():
			if data.get('salary'):
				obj = RegularEmployee.objects.get(employee=employee)
				employee.first_name = data['first_name']
				employee.last_name = data['last_name']
				employee.phone_number = data['phone_number']
				employee.save()
				obj.salary = data['salary']
				obj.save()
			elif data.get('graduated_from'):
				obj = DirectiveEmployee.objects.get(employee=employee)
				employee.first_name = data['first_name']
				employee.last_name = data['last_name']
				employee.phone_number = data['phone_number']
				employee.save()
				obj.graduated_from = data['graduated_from']
				obj.save()
			messages.success(request, '¡El empleado ha sido actualizado!')
			return HttpResponseRedirect(reverse('employees:employee_detail', kwargs={'slug': employee.slug}))
	else:
		try:
			obj = DirectiveEmployee.objects.get(employee=employee)
			emp_type = 'directive'
		except ObjectDoesNotExist as e:
			try:
				obj = RegularEmployee.objects.get(employee=employee)
				emp_type = 'regular'
			except ObjectDoesNotExist as e:
				return None
		if emp_type == 'directive':
			emp_form = DirectiveEmployeeForm(instance=employee)
			emp_form.fields['graduated_from'].initial = obj.graduated_from
		elif emp_type == 'regular':
			emp_form = RegularEmployeeForm(instance=employee)
			emp_form.fields['salary'].initial = obj.salary
		return render(request, 'employees/employee_form.html', {'form': emp_form, 'type': emp_type})


class EmployeeDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
	model = Employee

	def get_success_url(self):
		messages.success(self.request, '¡El empleado ha sido eliminado exitosamente!')
		return reverse_lazy('employees:employees_list')

employees/templates/employees/employee_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}The Star Rover - Eliminar Empleado{% endblock %}
{% block content %}
<div class="container-fluid">
	<div class="row mx-3 my-3">
		<div class="col-lg-12 col-xl-10 offset-xl-1 text-center">
			<h1 class="style-script display-4 text-red">Eliminar a {{ object.first_name }} {{ object.last_name }}</h1>
			<p class="lead">Haz clic en el botón de abajo para eliminar el empleado.</p>
			<hr>
			<button class="btn btn-lg btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">Eliminar a {{ object.first_name }} {{ object.last_name }}</button>
		</div>
	</div>
</div>
{% endblock %}
{% block modal %}
<div class="modal fade" id="deleteModal" role="dialog">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body text-center align-items-center">
                <h3>¡Cuidado!</h3>
                <p>
                	¿Realmente deseas eliminar a {{ object.first_name }} {{ object.last_name }}? Recuerda que <span class="text-danger">esta acción no puede dehacerse.</span>
                </p>
                <hr>
                <form method="post">
                	{% csrf_token %}
	                <button type="submit" class="btn btn-primary">Sí, deseo eliminarlo.</button>
	                <a class="btn btn-secondary" href="{% url 'employees:employee_detail' object.slug %}">No. Quiero regresar.</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

employees/templates/employees/employee_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/vendor/dataTables.bootstrap4.css' %}">
<link rel="stylesheet" href="{% static 'css/vendor/responsive.bootstrap4.css' %}">
{% endblock %}
{% block title %}The Star Rover - {{ object.first_name }} {{ object.last_name }}{% endblock %}
{% block content %}
<div class="container-fluid">
	<div class="row mx-3 my-3">
		<div class="col-lg-12 col-xl-10 offset-xl-1">
			<h1 class="style-script display-4 text-red">Información de {{ object.first_name }} {{ object.last_name }}</h1>
			<p class="lead">Aquí podrás ver toda la información detallada de {{ object.first_name }} {{ object.last_name }}.</p>
			<hr>
			<div class="accordion" id="agenciaAccordion">
				<div class="card mb-0">
					<div class="card-header" id="headingOne">
						<h5 class="m-0">
							<a href="#collapseOne" class="custom-accordion-title d-block py-2"
								data-bs-toggle="collapse" aria-expanded="true" aria-controls="collapseOne">
								Información de empleado
							</a>
						</h5>
					</div>
					<div class="collapse show" id="collapseOne" data-bs-parent="#agenciaAccordion">
						<div class="card-body">
							<table class="table table-borderless table-hover table-light">
								<tbody>
									<tr>
										<td>
											<strong>Nombre</strong>
										</td>
										<td>
											{{ object.first_name }} {{ object.last_name }}
										</td>
									</tr>
									<tr>
										<td>
											<strong>Número de teléfono</strong>
										</td>
										<td>
											{{ object.phone_number }}
										</td>
									</tr>
									{% if detail.salary %}
									<tr>
										<td>
											<strong>Salario</strong>
										</td>
										<td>${{ detail.salary|intcomma }}</td>
									</tr>
									{% endif %}
									{% if detail.graduated_from %}
									<tr>
										<td>
											<strong>Graduado de</strong>
										</td>
										<td>{{ detail.graduated_from }}</td>
									</tr>
									{% endif %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
				<div class="card mb-0">
					<div class="card-header" id="headingTwo">
						<h5 class="m-0">
							<a href="#collapseTwo" class="custom-accordion-title d-block py-2"
								data-bs-toggle="collapse" aria-expanded="true" aria-controls="collapseTwo">
								Eventos asignados
							</a>
						</h5>
					</div>
					<div class="collapse" id="collapseTwo" data-bs-parent="#agenciaAccordion">
						<div class="card-body">
							<table class="table table-borderless table-hover table-light" id="basic-datatable">
								<thead>
									<tr>
										<th>Nombre</th>
										<th>País de origen</th>
										<th>Fecha de nacimiento</th>
										<th>Salario</th>
										<th></th>
									</tr>
								</thead>
								<tbody>
									{% for model in models %}
									<tr>
										<td>{{ model.first_name }} {{ model.last_name }}</td>
										<td>{{ model.country.name }}</td>
										<td>{{ model.birthday|date:"d-m-Y" }}</td>
										<td>${{ model.salary|intcomma }}</td>
										<td><a href="{% url 'models:model_detail' model.slug %}" class="btn btn-outline-primary btn-sm">Detalle</a></td>
									</tr>
									{% empty %}
									<tr>
										<td colspan="4">
											<strong class="text-red text-center align-items-center">No hay modelos pertenecientes a esta agencia.</strong>
										</td>
									</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
			<div class="row mt-3">
				<div class="col">
					<a href="{% url 'employees:employee_edit' object.slug %}" class="btn btn-warning me-1">Editar datos de empleado</a>
					<a href="{% url 'employees:employee_delete' object.slug %}" class="btn btn-danger">Eliminar empleado</a>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block js %}
<!-- Datatables js -->
<script src="{% static 'js/vendor/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/vendor/dataTables.bootstrap4.js' %}"></script>
<script src="{% static 'js/vendor/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'js/vendor/responsive.bootstrap4.min.js' %}"></script>

<!-- Datatable Init js -->
<script src="{% static 'js/pages/demo.datatable-init.js' %}"></script>

{% endblock %}

employees/templates/employees/employee_form.html
{% extends 'base.html' %}
{% load static %}
{% block title %}The Star Rover - Registrar Empleado{% endblock %}
{% block content %}
<div class="container-fluid">
	<div class="row mx-3 my-3">
		<div class="col-lg-12 col-xl-10 offset-xl-1">
			<h1 class="style-script display-4 text-red">
				Registrar empleado
			</h1>
			<p class="lead">Usa el formulario de abajo para registrar un empleado nuevo.
			{% if form.non_field_errors %}
			<div class="alert alert-danger">
				<ul>
					{% for error in form.non_field_errors %}
					<li>{{ error }}</li>
					{% endfor %}
				</ul>
			</div>
			{% endif %}
			<form method="post">
				{% csrf_token %}
				<div class="mb-2">
					<label for="{{ form.first_name.id_for_label }}">{{ form.first_name.label }}</label>
					{{ form.first_name }}
					<div class="valid-feedback">
						¡Se ve bien!
					</div>
					<div class="invalid-feedback">
						{{ form.first_name.errors }}
					</div>
				</div>
				<div class="mb-2">
					<label for="{{ form.last_name.id_for_label }}">{{ form.last_name.label }}</label>
					{{ form.last_name }}
					<div class="valid-feedback">
						¡Se ve bien!
					</div>
					<div class="invalid-feedback">
						{{ form.last_name.errors }}
					</div>
				</div>
				<div class="mb-2">
					<label for="{{ form.phone_number.id_for_label }}">{{ form.phone_number.label }}</label>
					{{ form.phone_number }}
					<div class="valid-feedback">
						¡Se ve bien!
					</div>
					<div class="invalid-feedback">
						{{ form.phone_number.errors }}
					</div>
				</div>
				{% if type == 'regular' %}
				<div class="mb-2">
					<label for="{{ form.salary.id_for_label }}">{{ form.salary.label }}</label>
					{{ form.salary }}
					<div class="valid-feedback">
						¡Se ve bien!
					</div>
					<div class="invalid-feedback">
						{{ form.salary.errors }}
					</div>
				</div>
				{% elif type == 'directive' %}
				<div class="mb-2">
					<label for="{{ form.graduated_from.id_for_label }}">{{ form.graduated_from.label }}</label>
					{{ form.graduated_from }}
					<div class="valid-feedback">
						¡Se ve bien!
					</div>
					<div class="invalid-feedback">
						{{ form.graduated_from.errors }}
					</div>
				</div>
				{% endif %}
				<button type="submit" class="btn btn-primary">Guardar empleado</button>
			</form>
		</div>
	</div>
</div>
{% endblock %}

employees/templates/employees/employee_list.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/vendor/dataTables.bootstrap4.css' %}">
<link rel="stylesheet" href="{% static 'css/vendor/responsive.bootstrap4.css' %}">
<link href="{% static 'css/vendor/buttons.bootstrap4.css' %}" rel="stylesheet" type="text/css" />
{% endblock %}
{% block title %}The Star Rover - Todos los empleados{% endblock %}
{% block content %}
<div class="container-fluid">
	<div class="row mx-3 my-3">
		<div class="col-lg-12 col-xl-10 offset-xl-1">
			<h1 class="style-script display-4 text-red">Todos los empleados</h1>
			<p class="lead">Aquí encontrarás la lista de todos los empleados registrados.</p>
			<table class="table table-striped dt-responsive nowrap w-100" id="basic-datatable">
				<thead>
					<tr>
						<th>Id</th>
						<th>Nombre</th>
						<th>Numero de telefono</th>
						<th>Tipo de empleado</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					{% for employee in object_list %}
					<tr>
						
						<td>{{ employee.id }}</td>
						<td>{{ employee.first_name }} {{ employee.last_name }}</td>
						<td>{{ employee.phone_number }}</td>
						<td>{{ employee.get_type }}</td>
						<td><a href="{% url 'employees:employee_detail' employee.slug %}" class="btn btn-outline-primary btn-sm">Detalle</a></td>
					</tr>
					{% empty %}
					<tr>
						<td colspan="4"><span class="text-red">No hay empleados registrados. Registra uno <a href="{% url 'employees:regular_create' %}">aquí.</a></span></td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}
{% block js %}
<!-- Datatables js -->
<script src="{% static 'js/vendor/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/vendor/dataTables.bootstrap4.js' %}"></script>
<script src="{% static 'js/vendor/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'js/vendor/responsive.bootstrap4.min.js' %}"></script>

<!-- Datatable Init js -->
<script src="{% static 'js/pages/demo.datatable-init.js' %}"></script>

{% endblock %}